/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AirTicketing;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class UserRegistration extends javax.swing.JFrame {

    /**
     * Creates new form UserRegistration
     */
    public UserRegistration() {
        initComponents();
        this.setBounds(500, 200, 600, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbx_name = new javax.swing.JTextField();
        txtbx_number = new javax.swing.JTextField();
        txtbx_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtbx_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setText("ATBS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 10, 60, 30);

        jLabel2.setText("User Registration");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 130, 18);

        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 70, 49, 18);

        txtbx_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txtbx_name);
        txtbx_name.setBounds(250, 60, 190, 34);

        txtbx_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbx_numberActionPerformed(evt);
            }
        });
        getContentPane().add(txtbx_number);
        txtbx_number.setBounds(250, 120, 190, 34);
        getContentPane().add(txtbx_email);
        txtbx_email.setBounds(250, 180, 190, 34);

        jLabel4.setText("Phone number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 130, 110, 18);

        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 190, 49, 18);
        getContentPane().add(txtbx_password);
        txtbx_password.setBounds(250, 240, 190, 34);

        jLabel6.setText("Password");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 250, 80, 18);

        btn_register.setText("register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register);
        btn_register.setBounds(190, 290, 180, 36);

        jLabel7.setText("Already registered? ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(110, 360, 160, 18);

        jButton2.setText("LogIn");
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 350, 80, 36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbx_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_nameActionPerformed

    private void txtbx_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbx_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbx_numberActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        dbconnect conn = new dbconnect();
        String name = txtbx_name.getText();
        String number = txtbx_number.getText();
        String email = txtbx_email.getText();
        String password = txtbx_password.getText();
        try {
            PreparedStatement ps = conn.con.prepareStatement("insert into user(name,number,email,password) values(?,?,?,?)");
            ps.setString(1, name);
            ps.setString(2, number);
            ps.setString(3, email);
            ps.setString(4, password);
            int r = ps.executeUpdate();
            if (r >= 1) {
                JOptionPane.showMessageDialog(null, "Succesfully completed registration");
            } else {
                JOptionPane.showMessageDialog(null, "Not registered");
            };
        } catch (Exception e) {
            System.out.println("Error found" + e);
        }


    }//GEN-LAST:event_btn_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtbx_email;
    private javax.swing.JTextField txtbx_name;
    private javax.swing.JTextField txtbx_number;
    private javax.swing.JPasswordField txtbx_password;
    // End of variables declaration//GEN-END:variables
}
